server:
  port: 8989
  context-path: /ddw
  jsp-servlet:
    init-parameters:
      development: true
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/ddw
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  mvc:
    view:
      prefix: /
      suffix: .jsp
  http:
    multipart:
      max-file-size: 10Mb
      max-request-size: 100mb

    encoding:
      charset: UTF-8
      force: true


mybatis:
  mapper-locations: /com.baizhi.dao/*.xml
  type-aliases-package: com.baizhi.entity

